### PR TITLE
fix UnicodeDecodeError when use multibyte OS such as Japanease

### PR DESCRIPTION
**Pull request by goingmywaynet**
I got UnicodeDecodeError on Japanese Windows OS with miniconda.

   File "fgpoliciestocsv.py", line 94, in parse
     for line in fd_input:
    UnicodeDecodeError: 'cp932' codec can't decode byte 0x83 in position 563: illegal multibyte sequence

could you marge this fix for multilingual environment.
regard

### CODE REVIEW

**Comment by maaaaz** [comment]
Hello @goingmywaynet,
Thanks for this finding.

Could you provide a small example of a multibyte OS configuration file (suc as Japanese) ?
I will work on a fix and I would like to test the fix.

Cheers.

**Comment by maaaaz** [comment]
Fixed in https://github.com/maaaaz/fgpoliciestocsv/commit/4496efa77de538642bf8ecf08c403cb65500b2e1

**Comment by goingmywaynet** [comment]
thank you for encoding fix !!

I'm sorry too late to res for your comment
> Could you provide a small example of a multibyte OS configuration file (such as Japanese) ?
> I will work on a fix and I would like to test it.

when my environment 

Python 3.7.6
>>> import locale
>>> locale.getpreferredencoding()
'cp932'

it cause UnicodeDecodeError

**Comment by maaaaz** [comment]
Do you confirm this fix works for you ?

**Comment by goingmywaynet** [comment]
Yes. It's work!! Thank you!!

**Pull request closed without merging**
